### ISSUE TITLE
Restart button not doing anything.

### ISSUE THREAD

**Issue by BeckettH** [lanre-mark/tictactoe#6]
The restart button isn’t working I noticed, at least on the 3x3 and 7x7 boards. :)

**Comment by BeckettH** [comment]
On the 5x5 board it started with O’s turn, but it wasn’t playing O’s turn, and I couldn’t play either. Maybe because I switched from another board in the middle of a game?

**Comment by lanre-mark** [comment]
@BeckettH thanks for taking time out to check the game and report an issue. It means a lot.

I will check the issues out.

**Comment by lanre-mark** [comment]
@BeckettH please try the game again. I've fixed the 'Restart Session' button and addressed the nifty simulated moves causing double characters in the same spot as **dulio** pointed out on the slack channel.
